USE maps_db;

INSERT INTO countries (id, country_name, continent)
VALUES (1, 'Afghanistan', 'Asia'),
       (2, 'Albania', 'Europe'),
       (3, 'Algeria', 'Africa'),
       (4, 'Andorra', 'Europe'),
       (5, 'Angola', 'Africa'),
       (6, 'Antigua and Barbuda', 'North America'),
       (7, 'Argentina', 'South America'),
       (8, 'Armenia', 'Asia'),
       (9, 'Australia', 'Oceania'),
       (10, 'Austria', 'Europe'),
       (11, 'Azerbaijan', 'Asia'),
       (12, 'Bahamas', 'North America'),
       (13, 'Bahrain', 'Asia'),
       (14, 'Bangladesh', 'Asia'),
       (15, 'Barbados', 'North America'),
       (16, 'Belarus', 'Europe'),
       (17, 'Belgium', 'Europe'),
       (18, 'Belize', 'North America'),
       (19, 'Benin', 'Africa'),
       (20, 'Bhutan', 'Asia'),
       (21, 'Bolivia', 'South America'),
       (22, 'Bosnia and Herz.', 'Europe'),
       (23, 'Botswana', 'Africa'),
       (24, 'Brazil', 'South America'),
       (25, 'Brunei', 'Asia'),
       (26, 'Bulgaria', 'Europe'),
       (27, 'Burkina Faso', 'Africa'),
       (28, 'Burundi', 'Africa'),
       (29, 'Cabo Verde', 'Africa'),
       (30, 'Cambodia', 'Asia'),
       (31, 'Cameroon', 'Africa'),
       (32, 'Canada', 'North America'),
       (33, 'Central African Rep.', 'Africa'),
       (34, 'Chad', 'Africa'),
       (35, 'Chile', 'South America'),
       (36, 'China', 'Asia'),
       (37, 'Colombia', 'South America'),
       (38, 'Comoros', 'Africa'),
       (39, 'Congo', 'Africa'),
       (40, 'Costa Rica', 'North America'),
       (41, 'Cote d\'Ivoire', 'Africa'),
       (42, 'Croatia', 'Europe'),
       (43, 'Cuba', 'North America'),
       (44, 'Cyprus', 'Europe'),
       (45, 'Czechia', 'Europe'),
       (46, 'Denmark', 'Europe'),
       (47, 'Djibouti', 'Africa'),
       (48, 'Dominica', 'North America'),
       (49, 'Dominican Rep.', 'North America'),
       (50, 'Ecuador', 'South America'),
       (51, 'Egypt', 'Africa'),
       (52, 'El Salvador', 'North America'),
       (53, 'Equatorial Guinea', 'Africa'),
       (54, 'Eritrea', 'Africa'),
       (55, 'Estonia', 'Europe'),
       (56, 'Swaziland', 'Africa'),
       (57, 'Ethiopia', 'Africa'),
       (58, 'Fiji', 'Oceania'),
       (59, 'Finland', 'Europe'),
       (60, 'France', 'Europe'),
       (61, 'Gabon', 'Africa'),
       (62, 'Gambia', 'Africa'),
       (63, 'Georgia', 'Asia'),
       (64, 'Germany', 'Europe'),
       (65, 'Ghana', 'Africa'),
       (66, 'Greece', 'Europe'),
       (67, 'Grenada', 'North America'),
       (68, 'Guatemala', 'North America'),
       (69, 'Eq. Guinea', 'Africa'),
       (70, 'Guinea - Bissau', 'Africa'),
       (71, 'Guyana', 'South America'),
       (72, 'Haiti', 'North America'),
       (73, 'Holy See', 'Europe'),
       (74, 'Honduras', 'North America'),
       (75, 'Hungary', 'Europe'),
       (76, 'Iceland', 'Europe'),
       (77, 'India', 'Asia'),
       (78, 'Indonesia', 'Asia'),
       (79, 'Iran', 'Asia'),
       (80, 'Iraq', 'Asia'),
       (81, 'Ireland', 'Europe'),
       (82, 'Israel', 'Asia'),
       (83, 'Italy', 'Europe'),
       (84, 'Jamaica', 'North America'),
       (85, 'Japan', 'Asia'),
       (86, 'Jordan', 'Asia'),
       (87, 'Kazakhstan', 'Asia'),
       (88, 'Kenya', 'Africa'),
       (89, 'Kiribati', 'Oceania'),
       (90, 'Kuwait', 'Asia'),
       (91, 'Kyrgyzstan', 'Asia'),
       (92, 'Lao PDR', 'Asia'),
       (93, 'Latvia', 'Europe'),
       (94, 'Lebanon', 'Asia'),
       (95, 'Lesotho', 'Africa'),
       (96, 'Liberia', 'Africa'),
       (97, 'Libya', 'Africa'),
       (98, 'Liechtenstein', 'Europe'),
       (99, 'Lithuania', 'Europe'),
       (100, 'Luxembourg', 'Europe'),
       (101, 'Madagascar', 'Africa'),
       (102, 'Malawi', 'Africa'),
       (103, 'Malaysia', 'Asia'),
       (104, 'Maldives', 'Asia'),
       (105, 'Mali', 'Africa'),
       (106, 'Malta', 'Europe'),
       (107, 'Marshall Islands', 'Oceania'),
       (108, 'Mauritania', 'Africa'),
       (109, 'Mauritius', 'Africa'),
       (110, 'Mexico', 'North America'),
       (111, 'Micronesia', 'Oceania'),
       (112, 'Moldova', 'Europe'),
       (113, 'Monaco', 'Europe'),
       (114, 'Mongolia', 'Asia'),
       (115, 'Montenegro', 'Europe'),
       (116, 'Morocco', 'Africa'),
       (117, 'Mozambique', 'Africa'),
       (118, 'Myanmar', 'Asia'),
       (119, 'Namibia', 'Africa'),
       (120, 'Nauru', 'Oceania'),
       (121, 'Nepal', 'Asia'),
       (122, 'Netherlands', 'Europe'),
       (123, 'New Zealand', 'Oceania'),
       (124, 'Nicaragua', 'North America'),
       (125, 'Niger', 'Africa'),
       (126, 'Nigeria', 'Africa'),
       (127, 'North Korea', 'Asia'),
       (128, 'Macedonia', 'Europe'),
       (129, 'Norway', 'Europe'),
       (130, 'Oman', 'Asia'),
       (131, 'Pakistan', 'Asia'),
       (132, 'Palau', 'Oceania'),
       (133, 'Panama', 'North America'),
       (134, 'Papua New Guinea', 'Oceania'),
       (135, 'Paraguay', 'South America'),
       (136, 'Peru', 'South America'),
       (137, 'Philippines', 'Asia'),
       (138, 'Poland', 'Europe'),
       (139, 'Portugal', 'Europe'),
       (140, 'Qatar', 'Asia'),
       (141, 'Romania', 'Europe'),
       (142, 'Russia', 'Europe'),
       (143, 'Rwanda', 'Africa'),
       (144, 'Saint Kitts and Nevis', 'North America'),
       (145, 'Saint Lucia', 'North America'),
       (146, 'Saint Vincent and the Grenadines', 'North America'),
       (147, 'Samoa', 'Oceania'),
       (148, 'San Marino', 'Europe'),
       (149, 'Sao Tome and Principe', 'Africa'),
       (150, 'Saudi Arabia', 'Asia'),
       (151, 'Senegal', 'Africa'),
       (152, 'Serbia', 'Europe'),
       (153, 'Seychelles', 'Africa'),
       (154, 'Sierra Leone', 'Africa'),
       (155, 'Singapore', 'Asia'),
       (156, 'Slovakia', 'Europe'),
       (157, 'Slovenia', 'Europe'),
       (158, 'Solomon Islands', 'Oceania'),
       (159, 'Somalia', 'Africa'),
       (160, 'South Africa', 'Africa'),
       (161, 'South Korea', 'Asia'),
       (162, 'S. Sudan', 'Africa'),
       (163, 'Spain', 'Europe'),
       (164, 'Sri Lanka', 'Asia'),
       (165, 'Sudan', 'Africa'),
       (166, 'Suriname', 'South America'),
       (167, 'Sweden', 'Europe'),
       (168, 'Switzerland', 'Europe'),
       (169, 'Syria', 'Asia'),
       (170, 'Tajikistan', 'Asia'),
       (171, 'Tanzania', 'Africa'),
       (172, 'Thailand', 'Asia'),
       (173, 'Timor - Leste', 'Asia'),
       (174, 'Togo', 'Africa'),
       (175, 'Tonga', 'Oceania'),
       (176, 'Trinidad and Tobago', 'North America'),
       (177, 'Tunisia', 'Africa'),
       (178, 'Turkey', 'Asia'),
       (179, 'Turkmenistan', 'Asia'),
       (180, 'Tuvalu', 'Oceania'),
       (181, 'Uganda', 'Africa'),
       (182, 'Ukraine', 'Europe'),
       (183, 'United Arab Emirates', 'Asia'),
       (184, 'United Kingdom', 'Europe'),
       (185, 'United States', 'North America'),
       (186, 'Uruguay', 'South America'),
       (187, 'Uzbekistan', 'Asia'),
       (188, 'Vanuatu', 'Oceania'),
       (189, 'Venezuela', 'South America'),
       (190, 'Vietnam', 'Asia'),
       (191, 'Yemen', 'Asia'),
       (192, 'Zambia', 'Africa'),
       (193, 'Zimbabwe', 'Africa'),
       (194, 'Greenland', 'North America'),
       (195, 'Puerto Rico', 'North America'),
       (196, 'W. Sahara', 'Africa'),
       (197, 'Dem. Rep. Congo', 'Africa'),
       (198, 'Somaliland', 'Africa'),
       (199, 'Palestine', 'Asia'),
       (200, 'Kosovo', 'Europe');